export const GET_PRODUCTS_DATA_LIST_BEGIN = 'GET_PRODUCTS_DATA_LIST_BEGIN';
export const GET_PRODUCTS_DATA_LIST_SUCCESS = 'GET_PRODUCTS_DATA_LIST_SUCCESS';
export const GET_PRODUCTS_DATA_LIST_FAILED = 'GET_PRODUCTS_DATA_LIST_FAILED';

export const GET_SORT_PRODUCTS_BEGIN = 'GET_SORT_PRODUCTS_BEGIN';
export const GET_SORT_PRODUCTS_SUCCESS = 'GET_SORT_PRODUCTS_SUCCESS';
export const GET_SORT_PRODUCTS_FAILED = 'GET_SORT_PRODUCTS_FAILED';
